// AUTO-GENERATED by frontend/scripts/generate-analytics-events.mjs — do not edit manually.
// Source: docs/analytics-spec.md Sections 4-6 (`#### \`Event Name\`` headings).
// Run `npm run generate:analytics-events` after editing the spec and commit the result.
// Issue #677: single source-of-truth for all 34 spec event names.

/** All 34 event names from docs/analytics-spec.md Sections 4-6, in spec order. */
export const ANALYTICS_EVENTS = [
  'Page Viewed',
  'Send Form Viewed',
  'Send Form Started',
  'Send Form Field Changed',
  'Send Form Completed',
  'Payment Confirmation Viewed',
  'Wallet Connected',
  'Wallet Connection Failed',
  'Payment Confirmed',
  'Payment Created',
  'Payment Creation Failed',
  'Payment Success Viewed',
  'Claim Link Copied',
  'Claim Link Shared',
  'Dashboard Viewed',
  'Dashboard Filter Applied',
  'Payment Details Viewed',
  'Payment Cancelled',
  'Funds Reclaimed',
  'Claim Page Opened',
  'Claim Verified',
  'Claim CTA Clicked',
  'Wallet Address Screen Viewed',
  'Wallet Address Entered',
  'Wallet Address Validation Failed',
  'Claim Confirmation Viewed',
  'Claim Submitted',
  'Claim Succeeded',
  'Claim Failed',
  'Claim Success Viewed',
  'Sender Signup CTA Clicked',
  'Explorer Link Clicked',
  'Error Displayed',
  'Retry Clicked',
] as const;

/** Union of all spec event names. Referenced by frontend/lib/analytics.ts. */
export type AnalyticsEventName = (typeof ANALYTICS_EVENTS)[number];

/** Set-backed lookup for runtime validation / tests. */
export const ANALYTICS_EVENT_NAMES: ReadonlySet<AnalyticsEventName> = new Set(ANALYTICS_EVENTS);

/** Runtime guard: true when value is one of the 34 spec event names. */
export function isAnalyticsEventName(value: unknown): value is AnalyticsEventName {
  return typeof value === 'string' && ANALYTICS_EVENT_NAMES.has(value as AnalyticsEventName);
}

/** Expected spec event count. Bump together with the generator when the spec intentionally changes. */
export const ANALYTICS_EVENT_COUNT = 34 as const;
